# Site
repository: snowedev/snowedev.github.io
# favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: ì´ì›ì„
title: iOS Developer
email: leeewonseok@gmail.com
website: https://snowedev.github.io

# Dark Mode (true/false/never)
# darkmode: true

# Social links
# twitter_username: facespics
github_username:  snowedev
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ì´ì›ì„
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  > **URL of here**: https://snowedev.github.io

  ì•ˆë…•í•˜ì„¸ìš”, iOS ê°œë°œì„ ì¢‹ì•„í•˜ëŠ” ì´ì›ì„ì…ë‹ˆë‹¤.   

  ì „ ê°œë°œìë¡œì„œ,   
  - <mark>ìƒˆë¡œìš´ ê¸°ìˆ </mark>ì„ ë°°ìš°ëŠ” ê²ƒì— ì—´ê´‘í•˜ë©°, <mark>ë” ê¹”ë”í•˜ê³  ì •ëˆëœ ì½”ë“œ</mark>ë¥¼ ì‘ì„±í•˜ëŠ” ê²ƒì„ ì¢‹ì•„í•©ë‹ˆë‹¤.
  - <mark>ì†Œí†µ, í”¼ë“œë°±, ê°œë°œ, ì„±ì¥</mark>ì´ ìˆëŠ” ê°œë°œ ë¬¸í™”ë¥¼ ê°€ì¥ ì¢‹ì•„í•©ë‹ˆë‹¤.
  - <mark>í•™ìŠµ ì†ë„</mark>ê°€ ë¹ ë¥´ë‹¤ê³  ìë¶€í•©ë‹ˆë‹¤. í•˜ë‚˜ì˜ í•™ìŠµìœ¼ë¡œ ë˜ ë‹¤ë¥¸ í•™ìŠµì„ ì´ì–´ë‚˜ê°€ëŠ” ìŠµê´€ì´ ìˆìŠµë‹ˆë‹¤.
  - ì œê°€ ìƒê°í•˜ëŠ” <mark>ì¢‹ì€ ì½”ë“œ</mark>ëŠ” í”„ë¡œì íŠ¸ì˜ ì•„í‚¤í…ì³ë¥¼ í—¤ì¹˜ì§€ ì•Šìœ¼ë©° ê°€ë…ì„±ì´ ì¢‹ì€ ì½”ë“œì…ë‹ˆë‹¤.
  - ê¹ƒí—™ í˜¹ì€ ë¸”ë¡œê·¸ì— <mark>ê¸°ë¡</mark>í•˜ë©° ê³µë¶€í•˜ëŠ”ê²ƒì„ ì¢‹ì•„í•©ë‹ˆë‹¤.  

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: <img width="50px" style="border-radius:50%" src="https://user-images.githubusercontent.com/42789819/144747622-30206a57-4024-420d-8a88-2abbaa0b77f5.png"> Cherish</img>
        sub_title: ì—°ë½ì„ ì´ì–´ê°€ëŠ” ê°€ì¥ ì‰¬ìš´ ë°©ë²•
        caption: iOS Developer
        link: https://snowedev.github.io/2021/01/20/Restrospect/retrospect2/
        link_text: í”„ë¡œì íŠ¸ ê°œë°œ íšŒê³ 
        additional_links:
          - title:  appstore
            icon: fab fa-app-store
            url: https://apps.apple.com/us/app/id1557601516
          - title:  cherish github
            icon: fab fa-github
            url: https://github.com/TeamCherish/Cherish-iOS
          - title:  cherish instagram
            icon: fab fa-instagram
            url: https://www.instagram.com/cherish_ofcl/
        quote: >
          "ì¹œêµ¬ í˜¹ì€ ì§€ì¸ë“¤ì—ê²Œ ì—°ë½ ì¢€ í•˜ë¼ëŠ” ì†Œë¦¬ ìì£¼ ë“¤ìœ¼ì‹œë‚˜ìš”?"
        description: | # this will include new lines to allow paragraphs
          **execution period**
          - 2020.12.26 - 2021.01.16(APPJAM)
          - 2021.02.20 - 07.03(Released)  
          - 2021.07.03 ~ Maintenance

          **contribution**
          - 15ëª…(ê¸°íš 3, ë””ìì¸ 3, iOS 3, Android 3, Server 3)ì´ í•œ íŒ€ì„ ì´ë£¨ì—ˆìŠµë‹ˆë‹¤.
          - ì„œë¹„ìŠ¤ ë‚´ì—ì„œ íšŒì›ê°€ì…, ì˜¨ë³´ë”©, ì—°ë½í•˜ê¸°(ë¬¼ì£¼ê¸°)/ë¯¸ë£¨ê¸°, ë¦¬ë·°í•˜ê¸°, ìº˜ë¦°ë” ê¸°ëŠ¥ì„ ì£¼ë¡œ ê°œë°œí–ˆìŠµë‹ˆë‹¤.
          - ìƒì„¸í•œ ë‚´ìš©ì€ ì¢Œì¸¡ì˜ í”„ë¡œì íŠ¸ Github ë§í¬ì— ë‹´ì•˜ìŠµë‹ˆë‹¤.
          
          **result**
          - ğŸ† SOPT 27ê¸° APPJAM(ì¥ê¸°í•´ì»¤í†¤) <mark>ìµœìš°ìˆ˜ìƒ</mark>
          - ğŸ‰ ì•±ìŠ¤í† ì–´ 
            - <mark>ì—ë””í„° ì„ ì • ì´ë²ˆ ì£¼ ì£¼ëª©í•´ì•¼ í•  ì•±, ì´ë²ˆ ì£¼ ì¶”ì²œ ì•±</mark> ì„ ì •  
            - <mark>7ì›” ìµœê³ ì˜ ì•±</mark> ì„ ì •  
            - <mark>ì•±ìŠ¤í† ì–´ ì˜¤ëŠ˜ì˜ ì•±</mark> ì„ ì •

          **tech stack**
          - Swift, MVC
          - Storyboard â†’ SnapKit(ì§„í–‰ì¤‘)
          - Then, Alamofire, Kingfisher, Firebase(FCM)
          - FSCalendar, CallKit, MessageUI, Contacts

      - layout: left
        title: <img width="60px" style="border-radius:50%" src="https://user-images.githubusercontent.com/42789819/144747730-ed905665-8bf8-49b9-b17f-c5938cd6180a.png"> CA:PIN</img>
        sub_title: ì˜¤ëŠ˜ì€ ë¬´ìŠ¨ ì¹´í˜ê°€ì§€?
        caption: Server Developer
        link: https://snowedev.github.io/2021/07/27/Restrospect/retrospect3/
        link_text: í”„ë¡œì íŠ¸ ê°œë°œ íšŒê³ 
        additional_links:
          - title:  capin github
            icon: fab fa-github
            url: https://github.com/teamCA-PIN/CA-PIN_Server
          - title:  capin instagram
            icon: fab fa-instagram
            url: https://www.instagram.com/club_ca.pin/
        quote: >
          "ê²€ìƒ‰í•´ì„œ ë‚˜ì˜¤ëŠ” ì¹´í˜ê°€ ë‹¤ ë˜‘ê°™ê³  ê´‘ê³  ê°™ì•„ êº¼ë ¤ì§€ì§€ ì•Šìœ¼ì‹ ê°€ìš”?"
        description: | # this will include new lines to allow paragraphs
          **execution period**
          - 2021.06.26 - 07.16(APPJAM)
          - 08.27 ~ ì•±ê°œì„  ì‘ì—… ì¤‘
          - Release Soon...

          **contribution**
          - 14ëª…(ê¸°íš 2, ë””ìì¸ 3, iOS 3, Android 4, Server 2)ì´ í•œ íŒ€ì„ ì´ë£¨ì—ˆìŠµë‹ˆë‹¤.
          - ì„œë¹„ìŠ¤ ë‚´ì—ì„œ ì‚¬ìš©ì ì¸ì¦ ë° ì¡°íšŒ ê´€ë ¨, ì¹´í…Œê³ ë¦¬, CAFETI ê²€ì‚¬ ê´€ë ¨ ê°œë°œì„ ë‹´ë‹¹í–ˆìŠµë‹ˆë‹¤. 
          - ìƒì„¸í•œ ë‚´ìš©ì€ ì¢Œì¸¡ì˜ í”„ë¡œì íŠ¸ Github ë§í¬ì— ë‹´ì•˜ìŠµë‹ˆë‹¤.
          
          **result**
          - ğŸ† SOPT 28ê¸° APPJAM(ì¥ê¸°í•´ì»¤í†¤) <mark>ëŒ€ìƒ</mark>

          **tech stack**
          - TypeScript
          - Node.js(Express), AWS EC2, S3, PM2
          - MongoDB 

      - layout: left
        title: <img width="60px" style="border-radius:50%" src="https://user-images.githubusercontent.com/42789819/146631097-0f13924e-4814-410d-9d8e-08f8cd36af97.png"> Heimish</img>
        sub_title: ë‹¹ì‹ ì˜ ì•„ëŠ‘í•œ ì‹¬ë¦¬ìƒë‹´ ì±—ë´‡
        caption: iOS / Server Developer
        additional_links:
          - title:  heimish github
            icon: fab fa-github
            url: https://github.com/Team-Heimish/Heimish-iOS
        quote: >
          "ì‹œê°„, ì¥ì†Œ, ê¸ˆì•¡ì— êµ¬ì• ë°›ì§€ ì•ŠëŠ” ì‹¬ë¦¬ìƒë‹´ì‚¬"
        description: | # this will include new lines to allow paragraphs
          **execution period**
          - 2021.03.13 ~ 06.10(Dongguk Univ Capstone 4-1)

          **contribution**
          - í˜¼ì ê°œë°œì„ ì±…ì„ì§€ê³  ì§„í–‰í•˜ì˜€ìŠµë‹ˆë‹¤.
          - **iOS** ê°œë°œ ë° **Server** ê°œë°œì„ í•˜ì˜€ìŠµë‹ˆë‹¤.
          - ìƒì„¸í•œ ë‚´ìš©ì€ ì¢Œì¸¡ì˜ í”„ë¡œì íŠ¸ Github ë§í¬ì— ë‹´ì•˜ìŠµë‹ˆë‹¤.

          **tech stack**
          - **iOS**
            - Swift, MVC
            - Moya, SwiftLint, Realm, Google Dialogflow
          - **Server**
            - JavaScript, Node.js(express), AWS EC2, PM2

  - title: Activity # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: SOPT 27ê¸° iOS Part
        sub_title: ëŒ€í•™ìƒ ì—°í•© IT ë²¤ì²˜ì°½ì—…ë™ì•„ë¦¬
        caption: 2020.09.26 - 2021.01.16(ìˆ˜ë£Œ)
        additional_links:
          - title:  github
            icon: fab fa-github
            url: https://github.com/27thONSOPT-iOS/LeeWonSeok
          - title:  sopt instagram
            icon: fab fa-instagram
            url: https://www.instagram.com/sopt_official/
        quote: >
          "ê°œë°œì— ì—´ì •ì„ ê°€ì§€ê²Œ í•´ì£¼ì—ˆë˜ ê³„ê¸°"
        description: | # this will include new lines to allow paragraphs
            - 8ì£¼ê°„ íŒŒíŠ¸ì›ë“¤ê³¼ ì •í•´ì§„ ì»¤ë¦¬í˜ëŸ¼ì„ ë”°ë¼ í•™ìŠµí•˜ì˜€ìŠµë‹ˆë‹¤.
            - [5ì£¼ì°¨ì—ëŠ” ë””ìì´ë„ˆì™€ì˜ í˜‘ì—…ì„, 7ì£¼ì°¨ì—ëŠ” ì„œë²„ ê°œë°œìì™€ì˜ í˜‘ì—…](https://www.notion.so/snowedev/ON-SOPT-27-3b33324283464de9bce0d9e512ebe079#ee7b1659b0034173a0171b39d91828c0)ì„ ì§„í–‰í•˜ì˜€ìŠµë‹ˆë‹¤.
            - 6ì£¼ì°¨ì—ëŠ” ë™ì•„ë¦¬ ë‚´ ë¬´ë°• 2ì¼ í•´ì»¤í†¤ì— ì°¸ì—¬í•˜ì—¬ "MEMECHIN" ì´ë¼ëŠ” ë°ˆ ëª¨ì•„ë³´ê¸° ì•±ì„ ê°œë°œí•˜ì˜€ìŠµë‹ˆë‹¤.
            - 8ì£¼ê°„ì˜ ì„¸ë¯¸ë‚˜ ì¢…ë£Œ í›„ì—ëŠ” 3ì£¼ê°„ì˜ ì¥ê¸° í•´ì»¤í†¤ì¸ APPJAMì— ì°¸ì—¬í•˜ì—¬ "Cherish"ë¼ëŠ” ì„œë¹„ìŠ¤ë¥¼ ê°œë°œí•˜ì˜€ìŠµë‹ˆë‹¤.
            - ë™ì•„ë¦¬ì›ë“¤ê³¼ iOS ê¸°ì´ˆ ìŠ¤í„°ë””ì™€ [í´ë¡  ì½”ë”© ìŠ¤í„°ë””](https://www.notion.so/snowedev/Clone-Coding-Study-3570f80be4e64f5bb13561e236f866df#8fe817f03c4c4cdd9df6c1ae6a7510e0)ë¥¼ ê°œì„¤í•˜ì—¬ ì°¸ì—¬í•˜ì˜€ìŠµë‹ˆë‹¤.
          
      - layout: top
        title: SOPT 28ê¸° Server Part
        sub_title: ëŒ€í•™ìƒ ì—°í•© IT ë²¤ì²˜ì°½ì—…ë™ì•„ë¦¬
        caption: 2021.03.27 - 2021.07.31(ìˆ˜ë£Œ)
        additional_links:
          - title:  github
            icon: fab fa-github
            url: https://github.com/portfolio-toy
          - title:  sopt instagram
            icon: fab fa-instagram
            url: https://www.instagram.com/sopt_official/
        quote: >
          "ë” ì¢‹ì€ ê°œë°œìê°€ ë˜ê¸° ìœ„í•œ ìƒˆë¡œìš´ ë¶„ì•¼ ê²½í—˜"
        description: | # this will include new lines to allow paragraphs
            - 8ì£¼ê°„ íŒŒíŠ¸ì›ë“¤ê³¼ ì •í•´ì§„ ì»¤ë¦¬í˜ëŸ¼ì„ ë”°ë¼ í•™ìŠµí•˜ì˜€ìŠµë‹ˆë‹¤.
            - [6ì£¼ì°¨ì—ëŠ” ì›¹ í”„ë¡ íŠ¸ì—”ë“œ, ì•± ê°œë°œìì™€ì˜ í˜‘ì—…](https://www.notion.so/snowedev/BE-SOPT-28-fdeb94d1ebc847209c00eb8a2651e7d6#cf73fce4a4964a6199e019c6070b9549)ì„ ì§„í–‰í•˜ì˜€ìŠµë‹ˆë‹¤.
            - 8ì£¼ê°„ì˜ ì„¸ë¯¸ë‚˜ ì¢…ë£Œ í›„ì—ëŠ” 3ì£¼ê°„ì˜ ì¥ê¸° í•´ì»¤í†¤ì¸ APPJAMì— ì°¸ì—¬í•˜ì—¬ "CA:PIN"ë¼ëŠ” ì„œë¹„ìŠ¤ë¥¼ ê°œë°œí•˜ì˜€ìŠµë‹ˆë‹¤.
            - ë™ì•„ë¦¬ì›ë“¤ê³¼ [ì•Œê³ ë¦¬ì¦˜ ìŠ¤í„°ë””](https://github.com/snowedev/Algorithm)ì™€ [í…ìŠ¤ì³ ìŠ¤í„°ë””](https://github.com/TexBrother/TexBrother-Wonseok)ë¥¼ ê°œì„¤í•˜ì—¬ ì°¸ì—¬í•˜ì˜€ìŠµë‹ˆë‹¤.

  - title: Skill
    layout: list
    content:
      - layout: top-middle
        caption: ì‚¬ìš©ì¤‘ì´ê±°ë‚˜ ì‚¬ìš©í–ˆë˜ ê²½í—˜ì´ ìˆëŠ” ê¸°ìˆ ë“¤ì…ë‹ˆë‹¤.

      - layout: left
        title: iOS
        description: |
          - Swift, MVC
          - Storyboard, SnapKit, Texture
          - Alamofire, Moya
          - Then, Kingfisher, SwiftLint, Realm, Firebase, Google Dialogflow, Lottie, FSCalendar
          - Xcode
          - <mark>interesting</mark>: SwiftUI, RxSwift, MVVM, Instruments

      - layout: left
        title: Backend
        description: |
          - NodeJS(JavaScript, TypeScript)
          - mongoDB, MySQL
          - AWS EC2, S3
          - Visual Studio Code

      - layout: left
        title: Tool
        description: |
          - Zeplin, Figma
          - Slack, Notion, Discord, Gather
          - Postman, Swagger
          - GitKraken

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Dongguk University
        caption: 2020.03(í¸ì…) - 2022.02
        sub_title: ì •ë³´í†µì‹ ê³µí•™ì „ê³µ / ë²”ì£„ìˆ˜ì‚¬SW ì—°ê³„ì „ê³µ
        description: |
          GPA 4.13 / 4.5  
          TOEIC 960(~21.07.28)

      - layout: top
        title: Myongji College
        caption: 2015.02 - 2020.02(ì¡¸ì—…)
        sub_title: ì •ë³´í†µì‹ ê³µí•™ì „ê³µ
        description: |
          GPA 3.83 / 4.5

      - layout: top
        title: Dongsung HighSchool
        caption: 2012.03 - 2015.02(ì¡¸ì—…)
        sub_title: ìì—°ê³„ì—´ 
  
# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
